# Generated by Django 5.2.3 on 2025-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_curriculum',
            field=models.BooleanField(default=False, verbose_name='カリキュラム管理権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_groups',
            field=models.BooleanField(default=False, verbose_name='グループ管理権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_students',
            field=models.BooleanField(default=False, verbose_name='研修生管理権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_system',
            field=models.BooleanField(default=False, verbose_name='システム管理権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='ユーザー管理権限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_analytics',
            field=models.BooleanField(default=False, verbose_name='分析画面閲覧権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', '研修生'), ('training_admin', '研修管理者'), ('system_admin', 'システム管理者')], default='student', max_length=15),
        ),
    ]
