# Generated by Django 5.0.1 on 2025-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_customuser_can_manage_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='efficiency_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='進捗効率スコア'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='current_grade',
            field=models.CharField(choices=[('S', 'S級 (効率120%以上)'), ('A', 'A級 (効率100%以上)'), ('B', 'B級 (効率80%以上)'), ('C', 'C級 (効率60%以上)'), ('D', 'D級 (効率60%未満)')], max_length=1, verbose_name='現在の階級'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='current_grade',
            field=models.CharField(choices=[('S', 'S級 (効率120%以上)'), ('A', 'A級 (効率100%以上)'), ('B', 'B級 (効率80%以上)'), ('C', 'C級 (効率60%以上)'), ('D', 'D級 (効率60%未満)')], default='A', max_length=1, verbose_name='現在の階級'),
        ),
    ]
