# Generated by Django 5.0.1 on 2025-06-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userstats_efficiency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'training_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL, verbose_name='担当研修管理者'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='current_grade',
            field=models.CharField(choices=[('S', 'S級 (速度120%以上)'), ('A', 'A級 (速度100%以上)'), ('B', 'B級 (速度80%以上)'), ('C', 'C級 (速度60%以上)'), ('D', 'D級 (速度60%未満)')], max_length=1, verbose_name='現在の階級'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='current_grade',
            field=models.CharField(choices=[('S', 'S級 (速度120%以上)'), ('A', 'A級 (速度100%以上)'), ('B', 'B級 (速度80%以上)'), ('C', 'C級 (速度60%以上)'), ('D', 'D級 (速度60%未満)')], default='A', max_length=1, verbose_name='現在の階級'),
        ),
    ]
