# Generated by Django 5.2.3 on 2025-06-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_add_item_completed_and_weekly_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='feedback_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['training_admin', 'system_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_feedback', to=settings.AUTH_USER_MODEL, verbose_name='フィードバック提供者'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='feedback_provided',
            field=models.BooleanField(default=False, verbose_name='フィードバック提供済み'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='feedback_provided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='フィードバック提供日時'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='feedback_response',
            field=models.TextField(blank=True, max_length=1000, verbose_name='フィードバック内容'),
        ),
    ]
