# Generated by Django 5.2.3 on 2025-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_dailyprogress_feedback_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='ZIP形式のファイルのみアップロード可能です', null=True, upload_to='feedback_attachments/%Y/%m/%d/', verbose_name='添付ファイル（ZIP）'),
        ),
    ]
