# Generated by Django 5.0.1 on 2025-06-28 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_dailyprogress_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStudyHoursRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='週開始日')),
                ('week_end', models.DateField(verbose_name='週終了日')),
                ('rank', models.IntegerField(verbose_name='順位')),
                ('total_study_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='週間学習時間')),
                ('study_days', models.IntegerField(verbose_name='学習日数')),
                ('average_daily_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='一日平均学習時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_study_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '週間学習時間ランキング',
                'verbose_name_plural': '週間学習時間ランキング',
                'ordering': ['-week_start', 'rank'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
