# Generated by Django 5.0.1 on 2025-07-04 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_stamptype_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('grade_risk', '階級降格リスク'), ('no_report', '日報未提出'), ('long_delay', '大幅遅れ'), ('feedback_request', 'フィードバック要請')], max_length=20)),
                ('severity', models.CharField(choices=[('low', '軽微'), ('medium', '注意'), ('high', '重要'), ('critical', '緊急')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='progress_al_user_id_e2551b_idx'), models.Index(fields=['alert_type', 'is_active'], name='progress_al_alert_t_6bfad4_idx')],
            },
        ),
    ]
